server:
  port: 5050
spring:
  application:
    name: JobNotificationApplication
  datasource:
    url: jdbc:mysql://localhost:3306/Jobnotifications
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true